Repository ytturi/MortDeGana_Bot, pull requests merged in 2020-10, with the labels that each got.

#22 Add new options to moto quotes
  meldebot/mel/poll.py
Labels: hacktoberfest-accepted

#24 Use choice instead of randint
  meldebot/mel/flute.py
  meldebot/mel/gif.py
  meldebot/mel/text.py
Labels: hacktoberfest-accepted

#25 Update travis.yml to run with python 3.9
  .travis.yml
Labels: Ready :heavy_check_mark:, hacktoberfest-accepted

#27 Add catalan insults
  checks.sh
  meldebot/insults.py
  meldebot/mel/gif.py
  meldebot/mel/poll.py
  meldebot/mel/reply.py
  meldebot/mel/utils.py
Labels: Ready :heavy_check_mark:

#29 Add /gisce_meme command
  meldebot/bot.py
  meldebot/mel/conf.py
  meldebot/mel/meme.py
Labels: hacktoberfest-accepted

#30 Add commands to readme
  README.md
Labels: Ready :heavy_check_mark:, hacktoberfest-accepted

#31 Fix find for macOS
  checks.sh
Labels: Ready :heavy_check_mark:, bug

#28 Add types and typing tests
  .gitignore
  .travis.yml
  dev_requirements.txt
  meldebot/mel/conf.py
  meldebot/mel/flute.py
  meldebot/mel/gif.py
  meldebot/mel/meme.py
  meldebot/mel/poll.py
  meldebot/mel/reply.py
  meldebot/mel/text.py
  meldebot/mel/utils.py
  setup.cfg
Labels: Ready :heavy_check_mark:, hacktoberfest-accepted
